version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: pato-puto-mongo-db
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
